"""WS20 step 7: markdown digest of the rankings, written to
data/processed/margin_build/20_scoreboard/20_rankings_digest.md and pasted into the note.
"""
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[4]
OUT = ROOT / "data" / "processed" / "margin_build" / "20_scoreboard"

HEAD = ["adj_ebitda_margin_pct", "adj_ebitda_musd"]
LINES = ["cor_cash_musd", "ops_cash_musd", "pd_cash_musd", "sm_cash_musd",
         "ga_cash_ex_reserves_musd", "total_cash_costs_musd"]
BELOW = ["sbc_musd", "da_musd", "interest_income_musd", "diluted_shares_m",
         "eps_diluted", "net_income_musd", "op_income_musd", "fcf_musd", "fcf_margin_pct"]


def short(s):
    return (str(s).replace("baselines-margin", "base").replace("guide-policy-margin", "M3")
            .replace("driver-lines", "M1").replace("margin-ts", "M2")
            .replace("alt-augmented", "M4").replace("street-bias", "M5")
            .replace("cycle-flex", "M6").replace("below-ebitda", "M7"))


def table(df, n=3):
    lines = ["| # | method\\|object\\|spec | n | MAE | vs naive | vs street | params | surv |",
             "|---|---|---|---|---|---|---|---|"]
    for i, (_, r) in enumerate(df.head(n).iterrows(), 1):
        lines.append("| {} | {}\\|{}\\|{} | {:.0f} | {:.3f} | {} | {} | {:.0f} | {} |".format(
            i, short(r["method"]), r["object"], r["spec_id"], r["n"], r["mae"],
            f'{r["ratio_seasonal_naive"]:.2f}' if pd.notna(r["ratio_seasonal_naive"]) else "-",
            f'{r["ratio_street"]:.2f}' if pd.notna(r["ratio_street"]) else "-",
            r["n_params"], "y" if str(r["survives_both_windows"]).lower() in ("true", "yes") else "n"))
    return "\n".join(lines)


def main():
    r = pd.read_csv(OUT / "20_rankings_headline.csv")
    ln = pd.read_csv(OUT / "20_rankings_lines.csv")
    bl = pd.read_csv(OUT / "20_rankings_below_ebitda.csv")

    out = ["# WS20 rankings digest (auto-generated by build_digest.py)", ""]
    for tgt in HEAD:
        out.append(f"## {tgt}")
        for h in (0, 1, 2):
            for win in ("W1", "W2"):
                for w in ("equal", "recency"):
                    d = r[(r.target == tgt) & (r.horizon_q == h) & (r.window == win)
                          & (r.weighting == w)].sort_values("rank")
                    if d.empty:
                        continue
                    out.append(f"\n**h={h}, {win}, {w}-weighted** (n_objects {len(d)})\n")
                    out.append(table(d))
                    di = d[d.rank_independent.notna()].sort_values("rank_independent")
                    if len(di) and di.iloc[0]["method"] != d.iloc[0]["method"]:
                        out.append(f"\nBest Street-independent: {short(di.iloc[0]['method'])}|"
                                   f"{di.iloc[0]['object']}|{di.iloc[0]['spec_id']} "
                                   f"MAE {di.iloc[0]['mae']:.3f}")
        out.append("")
    for grp, df, name in (("lines", ln, LINES), ("below", bl, BELOW)):
        out.append(f"## {grp}")
        for tgt in name:
            for win in ("W1", "W2"):
                d = df[(df.target == tgt) & (df.horizon_q == 0) & (df.window == win)
                       & (df.weighting == "equal")].sort_values("rank")
                if d.empty:
                    continue
                out.append(f"\n**{tgt}, h=0, {win}, equal**\n")
                out.append(table(d))
        out.append("")
    (OUT / "20_rankings_digest.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote", OUT / "20_rankings_digest.md", len("\n".join(out)), "chars")


if __name__ == "__main__":
    main()
