export const meta = {
  name: 'github-altdata-integration-plan',
  description: 'Seven Fable lanes each map one sampled GitHub source family onto the team\'s existing ABNB objects (register, harness, nowcast, panels) and return an integration spec; then one critic checks feasibility',
  phases: [
    { title: 'Lanes', detail: 'one Fable agent per source family, reads samples + existing code, returns an integration spec' },
    { title: 'Critic', detail: 'one Fable agent challenges every spec for PIT, coverage, licence and effort realism' },
  ],
}

const WT = 'C:/Users/krish/citadel-abnb-ghcat'
const S = `${WT}/data/processed/github_altdata/samples`
const COMMON = `Repo worktree: ${WT} (branch krish/github-altdata-catalog, based on main). Read first: ${WT}/docs/github-altdata/CONTEXT.md (holdings and the 20 gaps) and ${WT}/docs/revenue-forecast-strategy/AGENT_BRIEF.md sections 1, 2, 5 and 6 (the chain the pitch runs on, what is established, the work packages WP-A..WP-X, the kill list). The team's rules that bind your plan: point-in-time or it does not count (refit at guide dates; two windows W1 = 1Q23+ n≈14 and W2 = 1Q24+ n≈10; a result must survive both); pre-register the pass line before running; register forecasts through the harness format (${WT}/analysis/src/forecast_methods/harness/README.md, FORMAT 1.0); copy never overwrite (new folder <pkg>_v2, new method names); the note-08 walk-forward protocol lives in ${WT}/analysis/src/adrq3/I0_protocol.py (expanding walk-forward from 1Q24, RMSE ratio vs naive last quarter / prior year / AR(1), permutation p, knowable-before-print flag) and the 598-feature machinery in ${WT}/analysis/src/overnight/08_altdata_backtests.py. Deadlines: memo 2 Oct 2026, print 5 Nov 2026 (never propose waiting for it). Never touch airbnb.com; scrapers of third-party sites are a human terms-of-service decision (WP-O); never use paid keys.

This is a PLAN, not an execution: do not run backtests, do not modify any existing file, do not commit. You may run small read-only Python (pandas/duckdb) on the sample files to confirm columns, date ranges and join keys, and read any repo file. Budget: about 40 tool calls.

Return an integration spec as structured output. For each source in your lane: (a) what object in the team's stack it feeds (a named KPI, a harness method, the L0 register, a panel CSV, a note) with the exact file paths it joins to and the join key; (b) the transformation from the sample's grain to that object's grain (columns, aggregation, calendar alignment, FX or seasonal handling); (c) coverage check: first and last date, whether it spans W1 and W2, publication lag, whether the value is knowable before 5 Nov, and whether it is point-in-time or a single vintage; (d) what it would be tested against and a pre-registerable pass line using the team's vocabulary (survivor / short-window survivor / corroboration / duplicate); (e) the full-pull command and size (from the sample's manifest.json how_pulled and full_dataset_size); (f) licence or ToS blockers and who decides; (g) effort in agent-days and the natural owner lane (Krish / Theo / Jessie / human) using the WP letters; (h) the very first command a fresh agent would run. Be concrete and honest: if a source duplicates something held, say so; if it cannot be point-in-time, say what it is good for instead (corroboration, exhibit, cohort).`

const SPEC = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    sources: { type: 'array', items: { type: 'object', properties: {
      slug: { type: 'string' }, repo_url: { type: 'string' },
      feeds: { type: 'string', description: 'named team object(s) + exact file paths + join key' },
      transformation: { type: 'string' },
      coverage: { type: 'string', description: 'first/last date, W1/W2 spanned?, publication lag, knowable before 5 Nov?, PIT or single vintage?' },
      test_and_pass_line: { type: 'string' },
      full_pull: { type: 'string', description: 'command + size' },
      blockers: { type: 'string', description: 'licence/ToS/access, and who decides' },
      effort_days: { type: 'number' }, owner_lane: { type: 'string' },
      first_command: { type: 'string' },
      verdict: { type: 'string', enum: ['build_now', 'build_if_time', 'exhibit_or_cohort_only', 'park'] },
      why: { type: 'string' },
    }, required: ['slug', 'repo_url', 'feeds', 'transformation', 'coverage', 'test_and_pass_line', 'full_pull', 'blockers', 'effort_days', 'owner_lane', 'first_command', 'verdict', 'why'] } },
    cross_source_notes: { type: 'string', description: 'how the sources in this lane combine, and anything the other lanes should know' },
  },
  required: ['lane', 'sources', 'cross_source_notes'],
}

const LANES = [
  { key: 'consensus_vintages', prompt: `LANE: point-in-time consensus and fundamentals (gap 4). Sources: ${S}/dolthub-post-no-preference-earnings-consensus-vintages (weekly revenue/EPS consensus snapshots for ABNB from Feb 2021, BKNG/EXPE from 2017), ${S}/pit-fundamentals-pit-harness, ${S}/defeatbeta-api-yahoo-finance-hf (earnings calendar, revenue breakdown, FX, transcripts). Existing objects: the L0 vintage register ${WT}/data/processed/forecast_methods/L0/L0_vintage_register.csv (read its header comments and columns: register_id, vendor, period, metric, value, unit, n_estimates, as_of_timestamp, url, source_path, role, pit_usable, vendor_attributed, note) and its append-only loader ${WT}/analysis/src/forecast_methods/L0/consensus_history_loader.py; the notes ${WT}/docs/revenue-forecast-strategy/05_backtests/A1_consensus_vintages.md and L0-spine.md; work packages WP-A (guide surprise needs consensus strictly before each guide date), WP-B (FY consensus revisions at 30/60/90 days), WP-G1 (LSEG history, human-gated), WP-M (weekly re-stamp). Questions to answer: does the DoltHub history give a vintage-stamped next-quarter and FY revenue consensus at each of the 14 W1 guide dates and how many of the 23 prints; how does it compare with the press-quote values already in the register (compute the overlap on the sample if the sample carries dates); is the licence usable; what is the exact append procedure that respects the append-only rule (dated backup first).` },
  { key: 'emea_volume', prompt: `LANE: EMEA and cross-border travel volume (gaps 7 and 10). Sources: ${S}/eurocontrol-daio-daily-flights (daily flights, 40 European states, 2019 to yesterday), ${S}/bts-canada-border-crossings-plus-intercept-survey (US-Canada monthly crossings 1996 to Jul 2026, port level from 2018), ${S}/dubai-det-tourism-csvs, ${S}/dwh-global-tourism-project (UNWTO-style annual tables). Existing objects: the regional nights panel ${WT}/data/processed/overnight/10_regional_panel_quarterly.csv (EMEA / NA / LatAm / APAC nights and revenue by quarter), the external-series machinery ${WT}/analysis/src/q3nowcast/G1_collect_external_series.py, G2_external_backtests.py, G3_rank_sources.py and its note ${WT}/research/notes/q3nowcast/G_external-sources-q3-read.md (which sources already survived: NTTO I-94 0.72-0.74x on nights; Eurostat platform nights 150-day lag; TSA fails), the govdata survey ${WT}/docs/govdata/BRIEF.md, work packages WP-C2 (macro/arrivals pulls, Theo) and WP-X (regional kernel and origin-destination FX). Questions: can daio be aggregated to a quarterly EMEA flight-volume y/y that is knowable before 5 Nov (Q3 complete by 1 Oct) and tested against EMEA nights y/y on both windows under G2's protocol; is it a duplicate of anything held (Eurocontrol is not in the repo); can Canada crossings test the 'Canadians returning' NA thesis (BEA foreign travel -9.9% in 3Q25, Canadians -31%) as a NA nights feature; what are Dubai and UNWTO good for beyond corroboration.` },
  { key: 'inside_airbnb_archives', prompt: `LANE: pre-2023 Inside Airbnb archives and the NYC Local Law 18 window (gap 1). Sources under ${S}: chicagoboothml-insideairbnb-2015-30cities, montera34-barcelona-insideairbnb-2015-2019 (34 dated snapshots Apr 2015-Mar 2019), joeydejager-nyc-2015, tmasjc-vienna-berlin-2017-plus-downloader, nyc-airbnb-listings-2024-01-05, databnb-10city-zillow-panel (Inside Airbnb dumps 2015-2020 for 10 US cities plus Zillow ZRI/ZHVI), boston-str-monitor-2015-2019, hf-buenosaires-airbnb-reviews, and the catalogue rows for estherkim99/cs1951a-final (244 raw monthly dumps, 8 US cities 2015-2020, ~5 GB, not sampled) and the 116-market Mar-May 2023 reviews mirror (find both in ${WT}/research/notes/github_altdata/catalog.csv and the note ${WT}/research/notes/github_altdata/2026-09-14_github-altdata-catalog.md gap 1 section). Existing objects: the reviews stays index ${WT}/analysis/src/q3nowcast/E1..E7 and its note ${WT}/research/notes/q3nowcast/E_reviews-stays-index.md (review-date counts over 123 markets as a nights nowcast, beats naive 0.68x; its history starts where the CDN starts, ~2025), the 13-city panel and like-for-like pairs from ${WT}/research/notes/2026-09-05_inside-airbnb-supply-panel.md and 2026-09-07_listing-churn-*.md, the party-size review pipeline ${WT}/analysis/src/abnb_party_size_reviews_v2.py, the NYC LL18 cohort in the regulatory package ${WT}/research/regulatory (NYC guest-nights -56.1% benchmark), and the memory that the CDN keeps ~1 year and NYC 2023-06..2024-03 dumps must be requested. Questions: which archive files carry review dates (reviews.csv) so the stays index can be extended back to 2015-2020 for the markets covered, and does that add scored quarters for ABNB (public KPIs exist from 1Q19 via the S-1 and quarterly from 1Q21) or only pre-IPO history useful for seasonality; can the Jan-2024 NYC snapshot plus the Mar-2023 reviews mirror bracket the LL18 enforcement (Sep 2023) to measure the listing and review-velocity drop directly; what the Zillow ZRI/ZHVI panel adds to host-supply economics; whether cs1951a-final (5 GB) is worth a full pull and for which cities.` },
  { key: 'booking_hf', prompt: `LANE: Booking.com's own Hugging Face releases as competitor and composition comparators (gaps 9 and 20). Sources: ${S}/hf-bookingcom-accommodation-reviews (1.6M 2023 reviews with guest_type and room_nights), ${S}/bookingcom-rectour24-accommodation-reviews, ${S}/bookingcom-multi-destination-trip-wsdm2021 (1.55M 2016 reservations with check-in/check-out, city, country, affiliate), ${S}/brightdata-booking-listings-hf and brightdata-booking-listings-sample-1001 (scraped listing snapshots, check licence), ${S}/hf-buenosaires-airbnb-reviews. Existing objects: the party-size programme (${WT}/analysis/src/abnb_party_size_reviews_v2.py, abnb_party_size_reviews_v2_aggregate.py, booking_party_composition.py, ${WT}/data/processed/abnb_party_size_reviews_quarterly.csv, the notes ${WT}/research/notes/2026-09-09_party-size-adr.md and 2026-09-09_seats-dilution.md, and ${WT}/data/raw/booking/rectour24_train_users.csv already held under a non-commercial licence), the length-of-stay work ${WT}/research/notes/2026-09-09_los_synthesis.md, the composition line in AGENT_BRIEF section 2 (geo mix -1.09 to -1.5pp, unit size +0.63pp, LOS +0.04, seats -0.5pp), and the peer read-through study (BKNG alternative-accommodation nights derived, WS11). Questions: which of these carry the fields needed for a party-size and LOS distribution by destination country and year that can be set beside Airbnb's review-derived party size (same grain, same year); does guest_type map to Airbnb's 'seats'; what is the cross-border share by origin/destination usable for WP-X; is anything here a time series or only single-year cross-sections (say which years); licence per file and whether the non-commercial clause matters for a student pitch; and whether the Bright Data snapshots are usable at all (scraped, ToS).` },
  { key: 'true_vintages_regulatory', prompt: `LANE: true point-in-time vintages and municipal registries (gaps 4 and 12). Sources: ${S}/toronto-str-registration-git-scrape (daily git-scraped Toronto STR registry since Feb 2024, ~917 commits), ${S}/fawazahmed0-fx-git-vintages (daily FX snapshots since Mar 2024), ${S}/upgo-vancouver-str-compliance, ${S}/istanbul-str-licensing-h3-2025, ${S}/texas-comptroller-hotel-occupancy-tax (property-level hotel occupancy tax to May 2026), ${S}/sideye-boston-occupancy-tax-imputed-nights. Existing objects: the regulatory package under ${WT}/research/regulatory (README.md, factor_register.md, source_index.md; identifier-matched cohorts for Barcelona HUTB and Maui; Austin daily active licences 527 dates from Jessie; the 20-event Monte Carlo), the FX schedule and the FX-lag method ${WT}/analysis/src/forecast_methods/fx_lag_v2 with note ${WT}/docs/revenue-forecast-strategy/05_backtests/fx-lag.md and B4_FX_EXHIBIT.md, WP-C2, WP-K, WP-L (policy monitor). Questions: can the Toronto git history be replayed into a daily active-registration series like Austin's (same columns as ${WT}/analysis/src/austin_str_daily.py output) and added as a fifth measured cohort; is the FX vintage repo useful given FRED/ECB already give daily spot (what does immutability add: the answer is probably 'only for reproducibility of the pull date', say so if true); does Texas HOT give a monthly hotel-revenue series by city that can be tested against NA nights or ADR under I0_protocol; is Boston's imputed-nights method transferable to our reviews index.` },
  { key: 'consumer_spend_engagement', prompt: `LANE: consumer spend, engagement and event proxies (gaps 5, 6, 11). Sources: ${S}/opportunity-insights-tracker (Affinity card spend national/state daily, ends Jun 2024), ${S}/augustliu-bnpl-merchant-dataset (BNPL merchant adoption + SEC panel incl. ABNB), ${S}/crux-top-lists-monthly-csv (Chrome UX popularity rank, monthly 2021-02 to 2026-08), ${S}/wikimedia-pageviews-attractions, ${S}/gharchive-org-github-event-archive and opendigger-github-org-monthly-metrics and airbnb-github-org (Airbnb engineering activity as a headcount/product proxy), ${S}/fifa-wc2026-schedule-venues and fifa-world-cup-2026-schedule (World Cup Jun-Jul 2026 inside 3Q26), ${S}/aarushisingh-pead-investor-attention (Google Trends SVI + earnings events). Existing objects: the predictive study and macro tests (${WT}/research/notes/2026-09-06_predictive-study.md: Michigan sentiment vs nights r -0.05; Google Trends 0/162 beat naive; TSA stopped predicting nights in 2024), the alt-data feature machinery ${WT}/analysis/src/overnight/08_altdata_backtests.py and note ${WT}/research/notes/overnight/08_altdata-index-and-backtests.md, BEA PCE travel panel under ${WT}/data/raw/bea, the RNPL thesis (WP-F: BNPL-like behaviour, cancellations), the H1-to-H2 bridge ${WT}/research/notes/2026-09-10_h1-to-h2-bridge.md (World Cup as a 3Q26 NA demand item?). Questions: does Affinity spend give a 'accommodation and food' or 'travel' category at state level that can be tested against NA nights on W1 (it ends Jun 2024, so say clearly it cannot cover W2 or the live quarter: corroboration or history only); is CrUX rank monthly for airbnb.com, booking.com, vrbo.com a usable engagement series and against which KPI; what would a World Cup host-city exposure table look like for the 3Q26 NA nights bridge (host cities x match dates x our Inside Airbnb markets); is the GitHub-activity proxy worth anything (probably an exhibit at most).` },
  { key: 'sec_toolchain_text', prompt: `LANE: SEC/EDGAR toolchain, ownership and transcript corpora (gaps 15, 18 and the WP-E1 cruise analogue). Sources: ${S}/dgunning-edgartools, ${S}/secfsdstools-sec-financial-statement-datasets, ${S}/edgar-crawler-edgar-corpus and edgar-crawler-item-section-extractor, ${S}/sec-data-xbrl-quarterly-segment-builder, ${S}/python-edgar-full-index-stitcher, ${S}/sec-cik-mapper-cik-ticker-crosswalk, ${S}/efebiskin-sec-form4-parser, ${S}/trade-copier-13f-berkshire-panel, ${S}/talsan-ishares-etf-holdings-history, ${S}/pchitral-etl-sec-edgar-10k-mda-corpus, ${S}/edgar-corpus-10k-sections-1993-2020, ${S}/lamini-earnings-calls-transcripts-2018-2023, ${S}/maec-multimodal-earnings-call-corpus, ${S}/ectsum-earnings-call-bullet-summaries, ${S}/qin-yang-earningscall-multimodal-2017, ${S}/sumaksharikaa-earnings-call-finbert-sentiment. Existing objects: the hand-built XBRL cost-line parser ${WT}/analysis/src/abnb_costlines_from_xbrl.py and the KPI panel builders, the peer 8-K parser (93 releases for BKNG/EXPE/MAR/HLT), the transcript analytics ${WT}/research/notes/2026-09-05_transcript-analytics.md (948 tone tests, none survive), the capital-return panel ${WT}/research/notes/2026-09-05_capital-return-panel.md, the inventory wish-list item '13F concentration history' and 'period-end fully diluted share count' (${WT}/docs/2026-09-06_research-inventory.md section 2.9 and 7.2), WP-E1 (NCLH advance ticket sales via balance sheet, Jessie), WP-E2 (BKNG/EXPE deferred merchant bookings). Questions: which single tool (edgartools vs secfsdstools vs edgar-crawler) most cheaply gives (i) NCLH ContractWithCustomerLiability / advance ticket sales 2015-2Q26 for WP-E1, (ii) BKNG/EXPE deferred merchant bookings for WP-E2, (iii) quarterly XBRL frames to replace the hand parser, (iv) a 13F holder-concentration history for ABNB from 2021, (v) Form 4 insider flow; which of these are pure duplicates of what the team already parses; and whether any transcript corpus adds ABNB or peer calls the team does not hold (the team has all 23 ABNB calls; pre-2023 peer calls may be new). Mark the transcript corpora 'park' unless they add peer history the tone study could use.` },
]

phase('Lanes')
const specs = await parallel(LANES.map(l => () =>
  agent(`${COMMON}\n\n${l.prompt}`, { label: `lane:${l.key}`, phase: 'Lanes', schema: SPEC, model: 'fable', effort: 'high' })
    .then(r => r ? { ...r, key: l.key } : null)))
const ok = specs.filter(Boolean)
log(`Lanes returned: ${ok.length}/${LANES.length}`)

phase('Critic')
const CRIT = { type: 'object', properties: {
  challenges: { type: 'array', items: { type: 'object', properties: {
    slug: { type: 'string' }, lane: { type: 'string' },
    issue: { type: 'string', description: 'the specific PIT / coverage / licence / duplicate / effort problem' },
    severity: { type: 'string', enum: ['kills_it', 'downgrade', 'note'] },
    revised_verdict: { type: 'string', enum: ['build_now', 'build_if_time', 'exhibit_or_cohort_only', 'park'] },
  }, required: ['slug', 'lane', 'issue', 'severity', 'revised_verdict'] } },
  ranked_build_now: { type: 'array', items: { type: 'string' }, description: 'slugs in the order the team should build them before 2 Oct, with one clause of why each' },
  sequencing_and_dependencies: { type: 'string' },
}, required: ['challenges', 'ranked_build_now', 'sequencing_and_dependencies'] }

const critic = await agent(`${COMMON}\n\nYou are the red team for seven integration specs written by other agents (JSON below). Challenge every source marked build_now or build_if_time: is it really point-in-time (a single vintage that only looks historical is not); does it span both W1 (1Q23+) and W2 (1Q24+) with enough scored quarters; is it knowable before 5 Nov; is the licence usable for a student competition memo; is it a duplicate of something in CONTEXT.md holdings; is the effort estimate honest given the 2 Oct memo; does the proposed pass line use the team's vocabulary and I0_protocol; does the plan violate copy-never-overwrite or the append-only register rule. Verify claims against the sample manifests under ${S}/<slug>/manifest.json and the repo files when the spec cites them. Then rank the build_now list for the two weeks before 2 Oct (at most eight items) and state dependencies (for example: the DoltHub register append must precede WP-A; the daio feature must be built through G1/G2 so it is scored like the other external series).\n\nSPECS:\n${JSON.stringify(ok, null, 1)}`, { label: 'critic', phase: 'Critic', schema: CRIT, model: 'fable', effort: 'high' })

return { lanes: ok, critic }