export const meta = {
  name: 'dolthub-consensus-into-l0',
  description: 'Build: append the DoltHub weekly Zacks-mirror consensus history to the L0 vintage register (backup first, new loader folder, frozen tests, T1 vendor-equivalence, note); then two independent verifiers',
  phases: [
    { title: 'Build', detail: 'one Fable agent: T0 provenance check, backup, L0_dolthub_v2/run.py, append, tests, panel, T1, registry baseline, note, WORKBOARD' },
    { title: 'Verify', detail: 'two Fable agents: invariants and numbers, each trying to refute the build' },
  ],
}

const WT = 'C:/Users/krish/citadel-abnb-ghcat'
const SAMPLE = `${WT}/data/processed/github_altdata/samples/dolthub-post-no-preference-earnings-consensus-vintages`
const L0SRC = `${WT}/analysis/src/forecast_methods/L0`
const L0DAT = `${WT}/data/processed/forecast_methods/L0`
const REG = `${L0DAT}/L0_vintage_register.csv`
const NEWSRC = `${WT}/analysis/src/forecast_methods/L0_dolthub_v2`
const NEWDAT = `${WT}/data/processed/forecast_methods/L0_dolthub_v2`
const NOTE = `${WT}/docs/revenue-forecast-strategy/05_backtests/G1b_dolthub_consensus_history.md`

const RULES = `Worktree ${WT} (branch krish/github-altdata-catalog). Rules that bind you (from CLAUDE.md and AGENT_BRIEF.md): copy never overwrite; the folder ${L0SRC} and the data folder ${L0DAT} are FROZEN except that ${REG} is append-only after a dated backup; new code goes in the NEW folder ${NEWSRC} (run.py exiting 0, README.md with the command) and new data in ${NEWDAT}; never edit consensus_history_loader.py, l0.py, test_l0.py, baselines__street.csv, targets.csv or calendar.csv; every consensus value carries vendor + timestamp; pre-register a pass line in the note BEFORE computing the result; a failed test is written up, not deleted; never commit to git (the orchestrator commits); no credentials, no paid keys. Python is \`python\` (pandas 3); run scripts from the worktree root. Plain prose in notes, no em-dashes.`

const BUILD_SCHEMA = { type: 'object', properties: {
  t0_provenance: { type: 'string', description: 'what dolt_log / AS OF checks ran, results, verdict (history immutable or not)' },
  backup_path: { type: 'string' },
  rows_before: { type: 'integer' }, rows_appended: { type: 'integer' }, rows_after: { type: 'integer' },
  vendor_string: { type: 'string' },
  tests_before: { type: 'string' }, tests_after: { type: 'string' },
  hard_rule_checks: { type: 'string', description: 'pre_guide_street 2026Q3, pit_consensus vendor=Zacks as of 2026-08-06, vendor=DoltHub as of 2026-08-06, duplicate ids, byte-identical prefix' },
  t1_result: { type: 'string', description: 'pre-registered pass line and the numbers: pre-guide cells n, median abs diff, sign agreement; at-print cells n, median abs diff; PASS or FAIL' },
  vendor_none_behaviour_change: { type: 'string', description: 'how many of the 22 guide-date and 23 print-date pit_consensus(vendor=None) revenue lookups change value after the append, and the largest change' },
  registry: { type: 'string', description: 'registry file written (or why not), score.py exit code, scoreboard delta' },
  nclh_pull: { type: 'string' },
  files_written: { type: 'array', items: { type: 'string' } },
  note_path: { type: 'string' },
  problems: { type: 'string' },
}, required: ['t0_provenance', 'backup_path', 'rows_before', 'rows_appended', 'rows_after', 'vendor_string', 'tests_before', 'tests_after', 'hard_rule_checks', 't1_result', 'vendor_none_behaviour_change', 'registry', 'nclh_pull', 'files_written', 'note_path', 'problems'] }

phase('Build')
const build = await agent(`${RULES}

TASK: put the DoltHub consensus history into the L0 vintage register as a second, vintage-stamped vendor. Read first: ${WT}/docs/github-altdata/INTEGRATION_PLAN.md (the DoltHub row and item 1 of the ranked list), ${SAMPLE}/manifest.json and README.md, ${L0SRC}/consensus_history_loader.py (the append-only loader; import and call its append(); reuse its HEADER and period_label logic), ${L0SRC}/l0.py (pit_consensus filters vendor with str.contains(case=False); pre_guide_street), ${L0SRC}/test_l0.py (frozen tests, including test_zacks_4740_is_not_usable_as_the_six_august_street and test_seeded_live_anchors), the header comments and columns of ${REG}, ${WT}/docs/revenue-forecast-strategy/05_backtests/A1_consensus_vintages.md, ${WT}/analysis/src/forecast_methods/harness/README.md (FORMAT 1.0) and ${WT}/data/processed/forecast_methods/registry/baselines__street.csv (the template for a Street baseline), and ${WT}/docs/revenue-forecast-strategy/AGENT_BRIEF.md section 7 (note template). The sample file ${SAMPLE}/sales_estimate_ABNB_BKNG_EXPE.csv already holds the COMPLETE ABNB sales_estimate table (1,160 rows: weekly Sunday snapshots 2021-02-07..2026-09-13, four period slots, consensus in whole USD, count, high, low, year_ago). Do NOT append EPS rows (basis differs from the register's press-quote adjusted EPS).

Steps, in order:
1. Pre-register in the note. Create ${NOTE} using the section 7 template and write the pass lines BEFORE computing anything: T0 provenance (history immutable: three AS OF spot checks equal current values, else only the latest snapshot may be appended); T1 vendor equivalence on the register's pre_guide cells that carry a value and a vintage (rows PG-* with pit_usable True): DoltHub latest snapshot strictly before the guide date (harness calendar.csv guide_date) vs the register value, PASS = median |diff|/register ≤ 1.0% AND sign(guide_mid − Street) agrees on at least 16 of 18 cells (guide_mid from calendar.csv); at-print cells (rows with role at_print, metric revenue): PASS = median |diff| ≤ 0.5%. Also pre-register the hard-rule invariants of step 6.
2. T0 provenance against DoltHub (keyless GET to https://www.dolthub.com/api/v1alpha1/post-no-preference/earnings/master?q=<urlencoded SQL>; the API returned 403 after ~40 requests in 20 minutes, so make at most 12 requests, 10 s apart, with curl -sL -G --data-urlencode). Queries: \`select commit_hash, committer, date, message from dolt_log order by date desc limit 5\` (and \`... order by date asc limit 3\` for the earliest commits); pick three historical ABNB snapshot dates (e.g. 2022-08-07, 2024-02-11, 2025-08-03) and for each find a commit whose date is within ~2 weeks after that snapshot (\`select commit_hash, date from dolt_log where date between '...' and '...' order by date limit 1\`), then \`select * from sales_estimate as of '<commit_hash>' where act_symbol='ABNB' and date='<snapshot>'\` and compare to the same rows in the current table / the sample. Record every query and result in the note. If the API is unreachable, say so and treat T0 as 'not run'; then still append but set the note's verdict to 'provenance unverified' and role note accordingly.
3. Backup: copy ${REG} to ${L0DAT}/L0_vintage_register.backup_2026-09-14.csv (byte copy). Count non-comment rows before.
4. Write ${NEWSRC}/run.py (+ README.md, + __init__.py if needed): read the sample CSV, keep act_symbol=='ABNB', build register rows with the loader's HEADER: period from period_end_date (quarter slots -> YYYYQn; year slots -> FYyyyy, assert month 12), value = consensus/1e6 (musd), n_estimates = int(count), as_of_timestamp = snapshot date, url = the exact DoltHub SQL API query URL from the manifest's source_urls, source_path = the sample CSV path relative to the worktree, role = 'pit_history', pit_usable = True, vendor_attributed = True, note = 'weekly Sunday snapshot; slot=<period>; high <high/1e6> / low <low/1e6> / year_ago <year_ago/1e6>; mirror of the Zacks free-page consensus (13 Sep 2026 snapshot equals the 11 Sep Zacks capture in this register to the dollar and count)'. register_id = 'PIT-{period}-revenue-DHPNP-{YYYYMMDD}'. VENDOR STRING MUST NOT CONTAIN THE SUBSTRING 'zacks' in any case: use exactly 'DoltHub post-no-preference/earnings'. run.py has a dry-run default and an --append flag that calls consensus_history_loader.append(rows) (import via importlib from ${L0SRC}; do not copy the loader); it also writes ${NEWDAT}/dolthub_weekly_panel.csv (date, slot, period, value_musd, n, high_musd, low_musd, year_ago_musd) and ${NEWDAT}/build_diagnostics.json. Exit 0.
5. Run the frozen tests BEFORE the append (\`python -m pytest ${L0SRC}/test_l0.py -q\` or \`python ${L0SRC}/test_l0.py\` if it is not pytest-shaped) and record pass/fail counts. Run run.py dry, inspect 5 rows, then run with --append.
6. After the append: re-run the frozen tests (must be identical to before); assert the first N non-comment lines of the register are byte-identical to the backup (compare the whole backup file to the prefix of the new file); assert zero duplicate register_ids; via l0: pre_guide_street('2026Q3') is LSEG 4610 @ 2026-08-06; pit_consensus('revenue','2026Q3','2026-08-06', vendor='Zacks') is None; pit_consensus('revenue','2026Q3','2026-08-06', vendor='DoltHub') returns the 2026-08-02 snapshot (report its value); pit_consensus('revenue','2026Q3','2026-09-11', vendor='Zacks') is still 4740. Then measure the behaviour change: for each of the 22 guide dates and 23 print dates in calendar.csv, compare pit_consensus('revenue', next quarter / the printed quarter, as_of=date, vendor=None) computed against the BACKUP file and against the NEW register (load both CSVs and apply the same selection logic in your own code, since l0 reads a fixed path) and report how many lookups change and the largest relative change. Write all of this into the note.
7. T1: compute the pre-registered comparison (pre-guide cells and at-print cells), one table with register_id, guide/print date, register vendor, register value, DoltHub snapshot date, DoltHub value, diff %, sign agreement. State PASS or FAIL against the pre-registered line. Also report the DoltHub values at the two register holes (PG-2021Q4 has no vintage; PG-2024Q3 has no vintage) as a second-vendor fallback WP-A may use, WITHOUT editing those rows.
8. Registry baseline: read harness/README.md and baselines__street.csv; if FORMAT 1.0 can be matched exactly, write a NEW registry file for a Street baseline under a new method name (e.g. baselines__street_dolthub.csv or whatever the README's naming rule requires) with one row per guide date using the DoltHub next-quarter revenue snapshot strictly before the guide date as the vintage-stamped Street value (street_vendor 'DoltHub post-no-preference/earnings', street_as_of = snapshot date), then run \`python ${WT}/analysis/src/forecast_methods/harness/score.py\` and record the exit code and whether every pre-existing scoreboard row is unchanged (diff scoreboard.csv before/after; back up scoreboard.csv to ${NEWDAT}/scoreboard_before.csv first). If the format cannot be matched with confidence, do not write the file; put a harness change request in the note instead.
9. NCLH for WP-E1: pull \`select * from sales_estimate where act_symbol='NCLH' order by date, period limit 500 offset 0\` (then 500, 1000 while rows keep coming, 60 s between calls, stop on 403) to ${NEWDAT}/dolthub_sales_estimate_NCLH.csv. Do NOT append NCLH to the register (it is ABNB-only). If the API refuses, record it and move on.
10. Finish the note (Verdict first paragraph in plain language; What ran with exact commands and exit codes; Results tables with n; What failed; Interpretation; Harness change requests; RESUME). Append ONE row to ${WT}/docs/revenue-forecast-strategy/WORKBOARD.md for this package (id G1b, 'DoltHub consensus history -> vintage register (stand-in for WP-G1)', owner Krish, status done/partial, branch krish/github-altdata-catalog, note path) and ONE WP-O line saying that quoting historical DoltHub values externally as Zacks needs a human decision; do not rewrite other rows. Return the structured output; keep problems honest.`,
  { label: 'build:dolthub', phase: 'Build', schema: BUILD_SCHEMA, model: 'fable', effort: 'high' })

if (!build) return { error: 'build agent returned null' }
log(`Build: appended ${build.rows_appended} rows (${build.rows_before} -> ${build.rows_after}); T1: ${(build.t1_result || '').slice(0, 120)}`)

phase('Verify')
const V_SCHEMA = { type: 'object', properties: {
  lens: { type: 'string' },
  checks: { type: 'array', items: { type: 'object', properties: {
    check: { type: 'string' }, result: { type: 'string', enum: ['confirmed', 'refuted', 'could_not_check'] }, evidence: { type: 'string' } }, required: ['check', 'result', 'evidence'] } },
  refutations: { type: 'array', items: { type: 'string' }, description: 'anything wrong that must be fixed before commit, concretely' },
  verdict: { type: 'string', enum: ['commit', 'fix_then_commit', 'do_not_commit'] },
}, required: ['lens', 'checks', 'refutations', 'verdict'] }

const buildSummary = JSON.stringify(build, null, 1)
const verifiers = await parallel([
  () => agent(`${RULES}

You are the INVARIANTS verifier for a build another agent just finished (its report is below). Try to refute it. Do not modify any file except writing your scratch scripts under ${WT}/data/processed/forecast_methods/L0_dolthub_v2/verify_invariants/ . Checks: (1) \`git -C "${WT}" status --short\` and \`git -C "${WT}" diff --stat\`: the ONLY tracked files changed must be ${REG} (appended lines only: \`git diff\` shows additions at the end and no deletions), WORKBOARD.md (added lines only), and possibly the harness scoreboard/registry outputs; nothing else under analysis/src/forecast_methods/L0/ or harness/ may be modified. (2) The backup file exists and equals the exact prefix of the new register (byte comparison). (3) Zero duplicate register_ids; every new row has vendor exactly 'DoltHub post-no-preference/earnings' (no 'zacks' substring case-insensitively), role pit_history, pit_usable True, a valid as_of_timestamp, metric revenue, unit musd, value between 500 and 20000. (4) Run the frozen tests yourself: \`python -m pytest ${L0SRC}/test_l0.py -q\` (or python ${L0SRC}/test_l0.py) and report the exact pass/fail counts. (5) Via l0 (sys.path insert ${L0SRC}; import l0): pre_guide_street('2026Q3') == LSEG 4610 @ 2026-08-06; pit_consensus('revenue','2026Q3','2026-08-06',vendor='Zacks') is None; pit_consensus('revenue','2026Q3','2026-09-11',vendor='Zacks') == 4740; pit_consensus('revenue','2026Q4','2026-09-12',vendor='Zacks') unchanged from the backup's answer; pit_consensus('revenue','2026Q3','2026-08-06',vendor='DoltHub') returns a 2026-08-02 row. (6) Re-derive the vendor=None behaviour change independently at the 22 guide dates and 23 print dates and compare to the build's claim. (7) If a registry file was written: score.py exits 0 when you run it, and every pre-existing scoreboard row is unchanged versus ${NEWDAT}/scoreboard_before.csv. (8) run.py exits 0 in dry-run mode and would append 0 new rows now (idempotent). Verdict: commit / fix_then_commit / do_not_commit with concrete refutations.

BUILD REPORT:
${buildSummary}`, { label: 'verify:invariants', phase: 'Verify', schema: V_SCHEMA, model: 'fable', effort: 'high' }),
  () => agent(`${RULES}

You are the NUMBERS verifier for a build another agent just finished (its report is below). Try to refute its numbers. Do not modify any file except scratch scripts under ${WT}/data/processed/forecast_methods/L0_dolthub_v2/verify_numbers/ . Checks: (1) From the raw sample ${SAMPLE}/sales_estimate_ABNB_BKNG_EXPE.csv (ABNB rows only) recompute independently: the number of snapshots and rows, the period mapping for 20 random rows (slot + period_end_date -> the register period label used in the appended rows; check FY rows and quarter rows, and the roll of slots across a print), values/1e6 vs the appended register rows (join on register_id), n_estimates. (2) Recompute T1 exactly as pre-registered in ${NOTE}: for every pre_guide row with pit_usable True in the BACKUP register (${L0DAT}/L0_vintage_register.backup_2026-09-14.csv), the DoltHub next-quarter (or matching period) snapshot strictly before the guide_date in ${WT}/data/processed/forecast_methods/harness/calendar.csv, the diff %, the sign agreement using guide_mid; and for the at_print revenue rows. Compare every number in the note's T1 table to yours; report any cell that differs by more than rounding. State whether the pre-registered PASS/FAIL call is right. (3) Check the note's T0 provenance claims: re-run ONE of the AS OF queries the note records (keyless GET, one request) and confirm the row equals what the note says; if the API refuses, mark could_not_check. (4) Check the two register holes (PG-2021Q4, PG-2024Q3): the DoltHub values the note reports for them are the latest snapshot strictly before those guide dates. (5) Read the note for kill-list violations or overclaims: it must not call DoltHub 'Zacks' in the vendor column, must not claim any forecast edge, must label everything as vintage-stamped history and T1 as corroboration/duplicate-grade. (6) Spot-check dolthub_weekly_panel.csv (row count, date range, one FY value against the raw file). Verdict: commit / fix_then_commit / do_not_commit with concrete refutations.

BUILD REPORT:
${buildSummary}`, { label: 'verify:numbers', phase: 'Verify', schema: V_SCHEMA, model: 'fable', effort: 'high' }),
])

return { build, verifiers: verifiers.filter(Boolean) }