import csv
import importlib.util
import json
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
BUILDER_PATH = ROOT / "docs" / "forecasting" / "abnb_ic_brief" / "build_assets.py"
REACTION_WORKBOOK = (
    ROOT
    / "outputs"
    / "01a065f3-9f9d-7c33-a034-621059cc8c6f"
    / "ABNB_edge_guidance_stock_reaction.xlsx"
)
ACTIVITY_PANEL = (
    ROOT
    / "outputs"
    / "01a065f3-9f9d-7c33-a034-621059cc8c6f"
    / "abnb_us_europe_guidance_panel.csv"
)


def load_builder():
    spec = importlib.util.spec_from_file_location("abnb_ic_brief_assets", BUILDER_PATH)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_compute_metrics_reproduces_the_reviewed_guidance_and_return_evidence():
    """Catch wrong joins, filters, or correlation definitions in the report builder."""
    builder = load_builder()

    metrics = builder.compute_metrics(REACTION_WORKBOOK, ACTIVITY_PANEL)

    assert metrics["guidance"]["events"] == 23
    assert metrics["guidance"]["numeric_ranges"] == 20
    assert metrics["activity_to_guidance"]["n"] == 16
    assert metrics["activity_to_guidance"]["pearson"] == pytest.approx(0.7841064502)
    assert metrics["activity_to_guidance"]["spearman"] == pytest.approx(0.3882352941)
    assert metrics["activity_to_guidance"]["pearson_improvement_vs_equal_weight"] == pytest.approx(
        0.0075269999
    )
    assert metrics["activity_to_guidance"]["pearson_improvement_vs_sfo"] == pytest.approx(
        0.0026888963
    )
    assert metrics["activity_to_guidance"]["acceleration_pearson"] == pytest.approx(
        -0.6270051348
    )
    assert metrics["activity_to_guidance"]["direction_concordance"] == pytest.approx(
        0.5333333333
    )
    assert metrics["guidance_to_return"]["yoy_pearson"] == pytest.approx(0.0763078150)
    assert metrics["guidance_to_return"]["yoy_n"] == 16
    assert metrics["guidance_to_return"]["acceleration_pearson"] == pytest.approx(
        0.0824419856
    )
    assert metrics["guidance_to_return"]["acceleration_n"] == 15
    assert metrics["guidance_to_return"]["sequential_pct_pearson"] == pytest.approx(
        0.0321227003
    )
    assert metrics["guidance_to_return"]["sequential_pct_n"] == 19
    assert metrics["guidance_to_return"]["direction_aligned"] == 7
    assert metrics["guidance_to_return"]["direction_total"] == 19


def test_expected_metric_guard_rejects_a_shortened_comparable_history(tmp_path):
    """Catch silent publication when the required n=16 composite history changes."""
    builder = load_builder()
    shortened = tmp_path / "shortened.csv"

    with ACTIVITY_PANEL.open(newline="", encoding="utf-8") as source:
        rows = list(csv.DictReader(source))
        fieldnames = list(rows[0])
    removed_prediction_id = next(
        row["prediction_id"]
        for row in rows
        if row["feature_id"] == "US_EMEA_REVENUE_WEIGHTED_COMPOSITE"
        and row["guidance_yoy_growth"]
    )
    kept = [row for row in rows if row["prediction_id"] != removed_prediction_id]
    with shortened.open("w", newline="", encoding="utf-8") as target:
        writer = csv.DictWriter(target, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(kept)

    metrics = builder.compute_metrics(REACTION_WORKBOOK, shortened)
    with pytest.raises(ValueError, match="activity_to_guidance.n"):
        builder.validate_expected_metrics(metrics)


def test_build_assets_emits_auditable_metrics_and_vector_figures(tmp_path):
    """Catch missing audit output or rasterized/non-PDF chart regressions."""
    builder = load_builder()

    builder.build_assets(REACTION_WORKBOOK, ACTIVITY_PANEL, tmp_path)

    audit = json.loads((tmp_path / "metrics.json").read_text(encoding="utf-8"))
    assert audit["evidence_cutoff"] == "2026-09-03"
    assert audit["metrics"]["activity_to_guidance"]["n"] == 16
    assert len(audit["inputs"]) == 4
    assert all(len(item["sha256"]) == 64 for item in audit["inputs"])
    assert (tmp_path / "metrics.tex").read_text(encoding="ascii").startswith(
        "% Generated by build_assets.py"
    )
    for figure_name in (
        "correlation_contrast.pdf",
        "guidance_vs_stock_performance.pdf",
        "event_excess_returns.pdf",
    ):
        assert (tmp_path / figure_name).read_bytes().startswith(b"%PDF-")
